require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'ProjectName' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'

  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  # pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'# bieu do
  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  # pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'
  # pod 'RNFS', :path => '../node_modules/react-native-fs'
  # pod 'rn-fetch-blob',
    # :path => '../node_modules/rn-fetch-blob'
  #react-native-permission2
  permissions_path = '../node_modules/react-native-permissions/ios'

  # pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  # pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  # pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  # pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  # pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  # pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
   pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  # pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
   pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  # pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  # pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  # pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  # pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"
   #react-native-permission2
  # pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  # target 'ShareExtension' do
  #   platform :ios, '9.0'
  
  #   pod 'react-native-config', :path => '../node_modules/react-native-config'
  
  #   # For extensions without React dependencies
  #   pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
  # end

  target 'ProjectNameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
